### ISSUE TITLE
Generate a PDF from asciidoc files

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs#1]
We need to generate PDF files based on asciidoc files. 
To do that we should first define a PDF Theme (https://docs.asciidoctor.org/pdf-converter/latest/theme/)

**Comment by zrgt** [comment]
@monsieuremre

**Comment by monsieuremre** [comment]
There seems to be no real 'automation' for html generation. I presume the same procedure/method is expected here for PDF generation. In that case, the following will be done:
* Define a YAML file for the PDF theme, probably by slightly adjusting an existing one in the public domain
* Generate the PDF files for given asciidocs manually
* Document the commands and respective options to execute in order to reproduce the generation process
* Push the YAML theme file, the generated PDF files and the updated documentation addressing how to reproduce the steps locally on demand

Is my understanding correct, or is there anything I am missing?

**Comment by zrgt** [comment]
@monsieuremre yes, that's correct.

Word files can be used as a reference for the PDF files you create. They should look the similar.

**Comment by monsieuremre** [comment]
See: https://github.com/rwth-iat/aas-specs/pull/3

**Comment by zrgt** [comment]
Done in #3
