### ISSUE TITLE
Fix Image/Table/Section links in asciidoc

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs#2]
Currently all references in Asciidoc for images, tables and sections are just a static text. 

We need to make these references interactive, such that on click the forwarding to the position with an according Image/Table/Section will be executed.
We need to define for each image, table referenced in text link names, which will be used for referencing in the text as links.

**Comment by zrgt** [comment]
This fix should be done in the stage of automatic generation of asciidoc from word in https://github.com/admin-shell-io/word2asciidoc

**Comment by monsieuremre** [comment]
I have managed to make the fix for figures and tables. I haven't got clauses and subclauses yet. It is all in a python script. For me to make further progress, or to push anything this issue has to be opened in the right place. This problem can't be addressed in this repository as you mentioned.

> This fix should be done in the stage of automatic generation of asciidoc from word in https://github.com/admin-shell-io/word2asciidoc

Please close this issue here and open a new one in the [relevant repository](https://github.com/admin-shell-io/word2asciidoc).

**Comment by zrgt** [comment]
Closed as opened in https://github.com/rwth-iat/word2asciidoc/issues/1
