### ISSUE TITLE
Transform the document IDTA-01003 to AsciiDoc

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs#4]
- [x] Transorm the [IDTA-01003](https://github.com/rwth-iat/aas-specs/blob/asciidoc_master/docs/AASiD/AASiD_3_iec61360/IDTA-01003-a-3-0_SpecificationAssetAdministrationShell_Part3a_DataSpecification_IEC61360.docx) to AsciiDoc with pandoc as given in the [README](https://github.com/rwth-iat/aas-specs/blob/asciidoc_master/docs/README.md#converting-word-documents-to-asciidoc)
- [x] After that run the scripts given in https://github.com/admin-shell-io/word2asciidoc/
- [x] Do manual bug fixes. Especially consider bugs in tables. As a reference use other asciidoc files already given in the project. Consider using regex search and replace in PyCharm as it is useful for manual fixes.
- [x] While doing the process you can also think about solving the issue #2 . May be you'll find some decision.
- [x] Fix label of a table on Page 32 in word document. Now it is labeled as an image. Label it as a table. And do the asciidoc generation with the fixed word document

**Comment by monsieuremre** [comment]
There are problems in the provided word document. Figure 12 is either non existent or it is a table. If it is not there, I need the image. If it is the table, I am going to have to do more manual fixing. Because asciidoctor automatically counts is as a table and not figure so all figures and tables afterwards are shifted in their index. Any reference or mention becomes meaningless.

What is the deal with figure 12 in the file? I am suspecting it is a table mislabeled as a figure but can't be sure.

**Comment by zrgt** [comment]
> There are problems in the provided word document. Figure 12 is either non existent or it is a table. If it is not there, I need the image. If it is the table, I am going to have to do more manual fixing. Because asciidoctor automatically counts is as a table and not figure so all figures and tables afterwards are shifted in their index. Any reference or mention becomes meaningless.
> 
> What is the deal with figure 12 in the file? I am suspecting it is a table mislabeled as a figure but can't be sure.

@monsieuremre I've checked the document and found out that indeed a table is mislabeled as a figure. 

To avoid manual fixes in asciidoc you can fix the wrong lable in the word document.

**Comment by monsieuremre** [comment]
>To avoid manual fixes in asciidoc you can fix the wrong lable in the word document.

I did that. I stumbled upon another major issue that is outside of my ability to fix. This is apart from the fact that the document lacks any standardization, consistency or compatibility within itself in the first place.

Figure 22 and 23 (23 and 24 before the fix) are the same picture, eventhough they are supposed to be describing different concepts. The second image probably has to be something with an arrow since it is 'association'. Whatever the source is, it needs to be fixed there. I cannot create images.

What am I supposed to do here? How do I get the missing image? Should I continue with the wrong image or delete it and have it be missing?

**Comment by monsieuremre** [comment]
Done in completion. Html and pdf files also generated. If there is something I missed, you can reopen the issue.

You can check it for yourself also on the [website](https://rwth-iat.github.io/aas-specs-antora/Data%20Specification/dev/index.html).

Side note:
I am not sure why [the same css file](https://github.com/rwth-iat/aas-specs-antora-ui/blob/main/src/css/aas-specs.css) in the antora ui makes the borders gray and thick when we use antora. This is not a problem when generating the html for the file manually. It might be because there is some other css file in the antora default ui, that overrides the option, that I missed. I will look into fixing it.

**Comment by monsieuremre** [comment]
Also the internal cross references are fully functional. You can check that out too. This was done using the script in the other branch of word2asciidoc. Script handles chapters and sections by itself completely, but for images and tables, everything is shifted in a not so predictable order, so there needs some manual fixes afterwards, but these fixes aren't complicated.
