### ISSUE TITLE
Integrate PUMLs instead of images

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs#7]
- Create new branch `IgGa/integrate-pumls` from `IDTA-01001-3-1_working`
- Place PUMLs from `https://github.com/zrgt/pyaas2puml/tree/main/output` in `documentation/IDTA-01001/modules/ROOT/partials/diagrams`
- Replace images from `documentation/IDTA-01001/modules/ROOT/images` with corresponding PUML diagrams from `https://github.com/zrgt/pyaas2puml/tree/main/output`
  - Preserve image numbers at the start of pumls
  - Find all usages of images and replace them with PUML reference

**Comment by monsieuremre** [comment]
> Find all usages of images and replace them with PUML reference

Far as I can tell not all images have a puml equivalent and the ordering of images does not seem to be consistent with the document. I have created the necessary structure to do the change and locally tried to do the replacements. I automatized it and the positions of images were completely mixed up as a result.

Also some images appear not to have their equivalents. At least it is not obvious.

I will push the folder structure to the my mock repo fork. The replacements won't be pushed just yet. The changes will be pushed once I figure out a how the ordering of images can be automatized. Worst case scenario I will have to do every single one of them automatically, searching all images and choosing the corresponding puml if there is one. Hopefully it won't come to that tho. Will report later with more details.

> Create new branch IgGa/integrate-pumls from IDTA-01001-3-1_working

I cloned the branch and then forked the mock repo and moved the structure to there. This structure is now among the submodels that will be integrated. I aimed to keep our testing sources centralized.

**Comment by monsieuremre** [comment]
Also @zrgt in my testing I had to use some files from older versions because for some reason your last commit seems to break the files. I think the contents of the files get literally deleted with the last commit. Did not look into file contents but with the last version you get a lot of emptiness and errors. I think the error with random placement might have been an error on my end, that came to be as I was fixing this other issue with versions, maybe while I was moving the old version files from different versions with different names into the current directory on my system. Directly using an old version without moving anything might solve the issue. I will look into it.

**Comment by zrgt** [comment]
@monsieuremre I have fixed the contetnt of PUMLs and its names/nums. Please check

**Comment by monsieuremre** [comment]
Completed.

For the html version see: https://rwth-iat.github.io/aas-specs-antora/part1puml/puml/index.html
For the pdf see: https://rwth-iat.github.io/aas-specs-antora/part1puml/puml/part-1-metamodel.pdf

Far as I can tell there are no issues at all with the puml files you provided. Some images could be also replaced, but they dont have the pumls in the repository. I don't know if this was intentional. Either way, puml files are now integrated. I did it in my own mock repo fork. So here: https://github.com/monsieuremre/aas-specs-mock/tree/patch-1

**Comment by zrgt** [comment]
@monsieuremre Good job! 

- [x] Create a branch in this repo with the changes you have already made.
- [x] Create PUML files manually, which were not present  in `pyaas2puml` repo

For the future: if you are working on changes/tests in some git project, please create a branch for this purpose in the same git repo. Do not make any tests regarding already present git repo in other repo. It is unnecessary and additional work if we want to integrate these changes.

**Comment by zrgt** [comment]
@monsieuremre Sorry, some puml nums in `https://github.com/zrgt/pyaas2puml/tree/main/output` were still not correct. I fixed them now

**Comment by zrgt** [comment]
@monsieuremre I have done the job. You don't need to work on this issue
